name: 📊 Generates Metrics
on:
  schedule:
    - cron: '0 0 * * *' # Run every night at midnight
  workflow_dispatch:
  
jobs:

  # All Metrics together
  all-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/all.svg
          # Options
          user: Lissy93
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_repositories: yes
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
          plugin_traffic: yes
          plugin_gists: yes
          plugin_discussions: yes

  # Main Metrics
  shorter-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/summary.svg
          user: Lissy93
          template: classic
          base: activity, community, repositories
          config_timezone: Europe/London
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: list
          plugin_sponsors_size: 28
          plugin_traffic: yes
          plugin_lines: yes
          plugin_discussions: yes
        
  # Sponsors Card
  sponsor-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/sponsors.svg
          # Options
          user: Lissy93
          template: classic
          base: ""
          config_timezone: Europe/London
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 36
  
  # 10 Years worth of contribution charts
  historical-contribuitions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/contributions.svg
          user: Lissy93
          template: classic
          base: ""
          config_timezone: Europe/London
          plugin_calendar: yes
          plugin_calendar_limit: 10
  
  # Ticket (Issue + PR) Follow Ups
  license-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/tickets.svg
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes

  
  # Coding Habits
  coding-habits-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/habits.svg
          user: Lissy93
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_days: 28
          plugin_habits_from: 500
          config_timezone: Europe/London

  
  # Total Stargazers
  stargazer-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/stargazers.svg
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist

  # Recent Activity
  activity-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/activity.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, public

  # Pinned Repositories
  repository-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/repositories.svg
          base: ""
          plugin_repositories_featured: >-
            lissy93/dashy, lissy93/personal-security-checklist, lissy93/go-apod, lissy93/dotfiles,
            lissy93/email-comparison, lissy93/awesome-selfhosted, lissy93/docker-tcpdump,
            lissy93/callisto-theme-standard-notes, lissy93/all-the-countries, lissy93/lissy93,
            lissy93/espanso-config, lissy93/minimal-terminal-prompt,
            lissy93/twitter-sentiment-visualisation, lissy93/hasami-shogi, lissy93/nfu,
            lissy93/anti-theft-charge, lissy93/pax, lissy93/md-cv-maker
  
  # StackOverflow Metrics
  stackoverflow-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/stackoverflow.svg
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 979052
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 2

  # Twitter Metrics
  twitter-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/twitter.svg
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_attachments: yes
          plugin_tweets_user: Lissy_Sykes
          plugin_tweets_limit: 5

  # RSS Feed
  blog-post-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/blog-posts.svg
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://notes.aliciasykes.com/feed
          plugin_rss_limit: 8

  # Wakatime Metrics
  wakatime-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/wakatime.svg
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_user: liss
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
