name: 📊 Generates Metrics
on:
  schedule:
    - cron: '0 0 * * *' # Run every night at midnight
  workflow_dispatch:
  
jobs:
  all-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/all-metrics.svg
          # Options
          user: Lissy93
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_support: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_repositories: yes
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
  shorter-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/shorter-metrics.svg
          user: Lissy93
          template: classic
          base: activity, community, repositories
          config_timezone: Europe/London
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: list
          plugin_sponsors_size: 28
          plugin_support: yes
        
  sponsor-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/sponsor-metrics.svg
          # Options
          user: Lissy93
          template: classic
          base: ""
          config_timezone: Europe/London
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 36
  historical-contribuitions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/hostorical-contributions-metrics.svg
          user: Lissy93
          template: classic
          base: ""
          config_timezone: Europe/London
          plugin_calendar: yes
          plugin_calendar_limit: 10
