name: 👔 Insert Repo List
on:
  schedule:
    - cron: '0 0 * * *' # Run every night at midnight
  workflow_dispatch:

env:
  GITHUB_NAME: lissy93
  GITHUB_EMAIL: liss-bot@d0h.co
  STARRED_NUM: 1000

jobs:
  add-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Run readme-repos-list
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "user:lissy93"
          max: 100
          path: ./REPO-LIST.md
          start: '<!--START_SECTION:my_github-->'
          end: '<!--END_SECTION:my_github-->'
          commit-message: '📂 Update repo list'
 
