# This is a basic workflow to help you get started with Actions

name: 🐍 Generate Snake Contribution GIF
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: assets/github-snake.gif
          svg_out_path: assets/github-snake.svg
